name: Build executables for gui.py

on:
  release:
    types: [created]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ 'windows-latest', 'ubuntu-latest', 'macos-latest' ]

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
      with:
        python-version: 3.7

    - run: pip install -r requirements.txt pyinstaller
    - run: pyinstaller --onefile -w gui.py
    
    - name: Publish Linux
      if: ${{ runner.os == 'Linux' }}
      run: |
        mv dist/* dist/real_division_GUI-Linux-x64
        cd dist/
        zip real_division_GUI-Linux-x64.zip *
        cd ..
        rm -r dist/real_division_GUI-Linux-x64
        
    - name: Publish Windows
      if: ${{ runner.os == 'Windows' }}
      run: |
        cd dist/
        rename gui.exe real_division_GUI-Windows-x64.exe
        zip real_division_GUI-Windows-x64.zip * -r
        del real_division_GUI-Windows-x64.exe
        cd ..
        
    - name: Publish macOS
      if: ${{ runner.os == 'macOS' }}
      run: |
        cd dist/
        mv gui.app real_division_GUI-macOS-x64.app
        rm gui
        zip real_division_GUI-macOS-x64.zip * -r
        rm -r real_division_GUI-macOS-x64.app
        cd ..

    - uses: softprops/action-gh-release@v1
      with:
        files: dist/*
